baseURL: /
enableRobotsTXT: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github
  tableOfContents:
    endLevel: 5
module:
  imports:
    - path: ../../shared/hugo
outputs:
  section:
    - HTML
    - RSS
params:
  copyright: Candid Development LLC
  copyrightLink: https://candid.dev
  disable_click2copy_chroma: true
  time_format_blog: 2006-01-02
taxonomies:
  tag: tags
  category: categories
